In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [290]:
matches = pd.read_csv('WorldCupMatches.csv',parse_dates=['Datetime'])
players = pd.read_csv('WorldCupPlayers.csv')
world_cups = pd.read_csv('WorldCups.csv')

### World Cup Matches Cleaning

In [291]:
matches.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,1930-07-14 14:50:00,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,1930-07-15 16:00:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [292]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4572 entries, 0 to 4571
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  852 non-null    float64
 1   Datetime              852 non-null    datetime64[ns]
 2   Stage                 852 non-null    object
 3   Stadium               852 non-null    object
 4   City                  852 non-null    object
 5   Home Team Name        852 non-null    object
 6   Home Team Goals       852 non-null    float64
 7   Away Team Goals       852 non-null    float64
 8   Away Team Name        852 non-null    object
 9   Win conditions        852 non-null    object
 10  Attendance            850 non-null    float64
 11  Half-time Home Goals  852 non-null    float64
 12  Half-time Away Goals  852 non-null    float64
 13  Referee               852 non-null    object
 14  Assistant 1           852 non-null    object
 15  Assistant 2           852 non-null    object
 16  RoundID               852 non-null    float64
 17  MatchID               852 non-null    float64
 18  Home Team Initials    852 non-null    object
 19  Away Team Initials    852 non-null    object
dtypes: datetime64[ns](1), float64(8), object(11)
memory usage: 714.5+ KB

In [293]:
# this dataset is strangely arranged thats why this is showing weird shape
matches.shape

(4572, 20)

In [294]:
# only 2 null values so removing it entirely
matches.dropna(inplace=True)
matches.shape

(850, 20)

In [295]:
# removing duplicates
print(matches.duplicated().sum())
matches.drop_duplicates(inplace=True)

15

## Changing data type from float to int

In [296]:
matches['Home Team Goals'] = matches['Home Team Goals'].astype('int')
matches['Away Team Goals'] = matches['Away Team Goals'].astype('int')
matches['Year'] = matches['Year'].astype('int')
matches['Attendance'] = matches['Attendance'].astype('int')
matches['Half-time Away Goals'] = matches['Half-time Away Goals'].astype('int')
matches['Half-time Home Goals'] = matches['Half-time Home Goals'].astype('int')
matches['MatchID'] = matches['MatchID'].astype('int')
matches['RoundID'] = matches['RoundID'].astype('int')

### Cleaning Data

In [297]:
# cleaning Home team Name with some unconsistency strings
matches['Home Team Name'] = matches['Home Team Name'].str.replace('rn">','').str.replace("C�te d'Ivoire","Côte d'Ivoire")

In [298]:
matches['Win conditions'] = matches['Win conditions'].str.strip()

In [299]:
# Stripping brfore replacing values
matches['Referee'] = matches['Referee'].str.strip()

matches.Referee.replace({"Oleg�rio BENQUEREN�A (POR)":"Olegário BENQUERENÇA (POR)"},inplace=True)
matches.Referee.replace({"C�neyt �AKIR (TUR)":"Cüneyt ÇAKIR (TUR)"},inplace=True)
matches.Referee.replace({"Bj�rn KUIPERS (NED)":"Björn KUIPERS (NED)"},inplace=True)
matches.Referee.replace({"St�phane LANNOY (FRA)":"Stéphane LANNOY (FRA)"},inplace=True)

In [300]:
matches.head(3)

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,1930-07-13 15:00:00,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,1930-07-14 12:45:00,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA

# Players Dataset

In [301]:
players.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN

In [302]:
players.shape

(37784, 9)

In [303]:
# Dropping duplicates because Event feature can't repeat in the same MatchID
print('Duplicate values: ',players.duplicated().sum())
players.drop_duplicates(inplace=True)

Duplicate values:  736

In [304]:
# only features: Position and Event has null values because these are events if the players made a goal, 
# recieved penealty, or any type of injury, what position was the player is in, blank values represent that no special 
# event happened 
players.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 37048 entries, 0 to 37047
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   RoundID        37048 non-null  int64
 1   MatchID        37048 non-null  int64
 2   Team Initials  37048 non-null  object
 3   Coach Name     37048 non-null  object
 4   Line-up        37048 non-null  object
 5   Shirt Number   37048 non-null  int64
 6   Player Name    37048 non-null  object
 7   Position       4018 non-null   object
 8   Event          8823 non-null   object
dtypes: int64(3), object(6)
memory usage: 2.8+ MB

In [305]:
# Stripping brfore replacing values
players['Coach Name'] = players['Coach Name'].str.strip()

players['Coach Name'].replace({"Sven-G�ran ERIKSSON (SWE)":"Sven-Göran ERIKSSON (SWE)"},inplace=True)
players['Coach Name'].replace({"J�rgen KLINSMANN (GER)":"JÜRGEN KLINSMANN (GER)"},inplace=True)
players['Coach Name'].replace({"Carlos QUEIR�S (POR)":"CARLOS QUEIRÓS (POR)"},inplace=True)
players['Coach Name'].replace({"Jos� P�KERMAN (ARG)":"JOSÉ PÉKERMAN (ARG)"},inplace=True)
players['Coach Name'].replace({"Lars LAGERB�CK (SWE)":"Lars LAGERBÄCK (SWE)"},inplace=True)

### Cleaning Player Name

In [306]:
# "�" these values are spanish word that is not recognised by the encoding that pandas use
players['Player Name'] = players['Player Name'].str.strip()
players_name = players[players['Player Name'].str.contains('�')]['Player Name'].unique()
players_name[:10]

array(['PEL� (Edson Arantes do Nascimento)', 'Hugo S�NCHEZ',
       'ROM�RIO (Rom�rio de Souza Faria)', 'CA�IZARES', 'M�LLER',
       'H�SSLER', 'MATTH�US', 'BJ�RNEBYE', 'Z� CARLOS', 'GON�ALVES'],
      dtype=object)

In [308]:
# This dict contains are all the strings that with "�" along with their fixed strings
replace_dict = {
    "M�LLER": "MÜLLER",
    "PEL� (Edson Arantes do Nascimento)": "PELÉ (Edson Arantes do Nascimento)",
    "�ZIL": "ÖZIL",
    "CA�IZARES": "CAÑIZARES",
    "Hugo S�NCHEZ": "Hugo SÁNCHEZ",
    "Z� ROBERTO": "ZÉ ROBERTO",
    "SIM�O": "SIMÃO",
    "GRO�KREUTZ": "GROßKREUTZ",
    "G�TZE": "GÖTZE",
    "H�WEDES": "HÖWEDES",
    "J�": "JÚ",
    "SCH�RRLE": "SCHÜRRLE",
    "ROM�RIO (Rom�rio de Souza Faria)": "ROMÁRIO (Romário de Souza Faria)",
    "LUIS�O": "LUISÃO",
    "UMA�A M.": "UMAÑA M.",
    "KAK�": "KAKÁ",
    "PIQU�": "PIQUÉ",
    "BOLA�OS C.": "BOLAÑOS C.",
    "L�CIO": "LÚCIO",
    "MATTH�US": "MATTHÄUS",
    "H�SSLER": "HÖSSLER",
    "URE�A M.": "UREÑA M.",
    "ACU�A": "ACUÑA",
    "GON�ALVES": "GONÇALVES",
    "C. ZU�IGA": "C. ZUÑIGA",
    "Z� CARLOS": "ZÉ CARLOS",
    "KIE�LING": "KIEßLING",
    "F. COENTR�O": "F. COENTRÃO",
    "BJ�RNEBYE": "BJØRNEBYE",
    "NU�EZ": "NUÑEZ",
    "JOSU�": "JOSUÉ",
    "SCH�R": "SCHR",
    "B�RKI": "BÜRKI",
    "CH. AR�NGUIZ": "CH. ARÁNGUIZ",
    "GUTI�RREZ": "GUTIÉRREZ",
    "W�RNS": "WÜRNS",
    "K�PKE": "KÖPKE",
    "VER�N": "VERÓN",
    "R. MU�OZ": "R. MUÑOZ",
    "C. PE�A": "C. PEÑA",
    "ZUBERB�HLER": "ZUBERBÜHLER",
    "�STENSTAD": "ØSTENSTAD",
    "SOLSKJ�R": "SOLSKJÆR",
    "CASTA�EDA": "CASTAÑEDA",
    "GROD�S": "GRODÉS",
    "ALVB�GE": "ALVBÅGE",
    "K�LLSTR�M": "KÄLLSTRÖM",
    "ALLB�CK": "ALLBÄCK",
    "MAND�UKI?": "MANDŽUKIĆ",
    "BE�I?": "BEŠIĆ",
    "C�CERES": "CÁCERES",
    "NU�EZ V.": "NUÑEZ V.",
    "BOLA�O": "BOLAÑO",
    "ETXEBERR�A": "ETXEBERRÍA",
    "OLEMB�": "OLEMBÉ",
    "MAHOUV�": "MAHOUVÉ",
    "PENS�E": "PENSÉE",
    "KOLA�INAC": "KOLAŠINAC",
    "MUJD�A": "MUJDŽA",
    "D�EKO": "DŽEKO",
    "JAVI MART�NEZ": "JAVI MARTÍNEZ",
    "VR�AJEVI?": "VRŠAJEVIĆ",
    "VRANJE�": "VRANJEŠ",
    "IBI�EVI?": "IBIŠEVIĆ",
    "SU�I?": "SUŠIĆ",
    "�UNJI?": "ŠUNJIĆ",
    "VI�?": "VIŠĆA",
    "HAD�I?": "HADŽIĆ",
    "ETAM�": "ETAMÉ",
    "WOM�": "WOMÉ",
    "�DER": "ŠDER",
    "F�BREGAS": "FÁBREGAS",
    "�IGI?": "ŠIGIĆ",
    "CA�IZA": "CAÑIZA",
    "M�RIO": "MÁRIO",
    "LAM�": "LAMÉ",
    "LOC�": "LOCÉ",
    "Z� KALANGA": "ZÉ KALANGA",
    "�ULER": "ŠULER",
    "�ELIGA": "ŠELIGA",
    "D�INI?": "DŽINIĆ",
    "MATAV�": "MATAVŽ",
    "MILIJA�": "MILIJAŠ",
    "AKW�": "AKWÉ",
    "TO�I?": "TOŠIĆ",
    "ANDR� MACANGA": "ANDRÉ MACANGA",
    "JO�O RICARDO": "JOÃO RICARDO",
    "S�RENSEN": "SØRENSEN",
    "KJ�R": "KJÆR",
    "J�RGENSEN": "JØRGENSEN",
    "GR�NKJ�R": "GRØNKJÆR",
    "KR�LDRUP": "KRØLDRUP",
    "W�LFLI": "WÖLFLI",
    "PERI�I?": "PERIĆ",
    "SUBA�I?": "SUBAŠIĆ",
    "CABA�AS": "CABAÑAS",
    "FL�VIO": "FLÁVIO",
    "VI�?A": "VIŠĆA",
}

# Using for loop to replace all the strange strings with the fixed values

for i,j in replace_dict.items():
    players['Player Name'].replace({i:j},inplace=True)

## Feature Extraction from "Event" column

In [309]:
# this Feature contain the event happened with their corrosponding time
# G11: G-> Goal;    11-> at 11 minutes from the start of the match
# I77: I-> Injury;  77-> at 77 minutes from the start of the match
players['Event'].value_counts().head(10)

OH46'    239
IH46'    200
Y1'       87
I77'      77
I78'      75
I73'      75
I72'      74
O75'      72
I74'      71
I75'      71
Name: Event, dtype: int64

In [310]:
# Extracting number of goal from the event
def goal_scored(row):
    if 'G' in row:
        return row.count('G')
    else:
        return 0

In [311]:
# stripping befor applying function
players['Event'] = players['Event'].str.strip()

# Filling Nan Values with 0 so that error don't occur
players['Event'].fillna('0',inplace=True)

# applying function
players['Goal Scored'] = players['Event'].apply(goal_scored)

In [312]:
players.shape

(37048, 10)

In [313]:
# cleaned players data
players.head()

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goal Scored
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,0,0
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,0,0
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,0,0

# Merging Cleaned Players and Matches dataset

In [322]:
final_df = matches.merge(players,on='MatchID')
final_df.head()

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID_x,MatchID,Home Team Initials,Away Team Initials,RoundID_y,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event,Goal Scored
0,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,201,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,0,0
1,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,201,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,0,0
2,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,201,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40',1
3,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,201,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70',1
4,1930,1930-07-13 15:00:00,Group 1,Pocitos,Montevideo,France,4,1,Mexico,,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX,201,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,0,0

# Exporting for analysis in Power Bi

In [323]:
final_df.to_csv('Cleaned_FiFa',index=True)